### PR TITLE
Add Norwegian stemmer

### PR DESCRIPTION
**Pull request by chrihunstad**

### CODE REVIEW

**Comment by JDemler** [comment]
Hey @chrihunstad,

thank you for this PR. Everything looks good so far. Just one little question:

Is there a reason why you removed the comments that help to debug in the compiled stemmer file? 

Cheers!

**Comment by chrihunstad** [comment]
I did not remove any comments, this was the output from running "make" in the snowball project.

Is there some kind of debug argument I can pass to generate the algorithm files with comments?

**Comment by JDemler** [comment]
Looked into it again... this changed with version 2.0.

**Comment by JDemler** [comment]
Changes published in version 1.2. 

Thanks again for the changes!

**Pull request merged**
